name: Release and Changelog

on:
  push:
    branches:
      - main

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install conventional-changelog-action
        uses: peter-evans/conventional-changelog-action@v2

      - name: Generate Changelog
        id: generate-changelog
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: |
            /^(feat|fix) #.*: .*/

  create-release:
    needs: generate-changelog
    runs-on: ubuntu-latest

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.generate-changelog.outputs.version }}
          release_name: Release ${{ steps.generate-changelog.outputs.version }}
          body: ${{ steps.generate-changelog.outputs.body }}
          draft: false
          prerelease: false
